ALTER TABLE "projects" ADD COLUMN "nota_media" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "projects" ADD COLUMN "upvotes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "feedbacks" ADD COLUMN "nota" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "feedbacks"
  ADD CONSTRAINT "feedbacks_nota_check" CHECK ("nota" BETWEEN 1 AND 5);
