-- AlterTable
ALTER TABLE "feedbacks" ADD COLUMN "nota" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "feedbacks" ALTER COLUMN "nota" DROP DEFAULT;

-- AlterTable
ALTER TABLE "projects" ADD COLUMN "upvotes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "projects" ADD COLUMN "nota_media" DOUBLE PRECISION NOT NULL DEFAULT 0;
